/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ASpin: typeof import('ant-design-vue/es')['Spin']
    Button: typeof import('./src/components/Button.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    ConfirmDelete: typeof import('./src/components/ConfirmDelete.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    InputField: typeof import('./src/components/InputField.vue')['default']
    LoginComponent: typeof import('./src/components/LoginComponent.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RegisterComponent: typeof import('./src/components/RegisterComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidenav: typeof import('./src/components/Sidenav.vue')['default']
    TableComponent: typeof import('./src/components/TableComponent.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
